modLoader="javafml"
loaderVersion="[4,)"

license="CC-BY-NC-4.0"

[[mods]]
modId="broken_chronicles"
version="${version}"
displayName="Broken Chronicles"
description='''收集散落在世界中的碎片化叙事并编录成册。
支持数据包注册 page / book / tag 三种文字记录：阅读即收录，物品销毁后条目仍保留。
可配置，支持多语言文本。'''

[[dependencies.broken_chronicles]]
modId="neoforge"
type="required"
versionRange="[21.1.248,)"
ordering="NONE"
side="BOTH"

[[dependencies.broken_chronicles]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
